server:
  port: ${main_port:9095}
  error:
    whitelabel.enabled: false
  servlet.context-path: /auth


mybatis-plus:
  # mybatis
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  # entity
  typeAliasesPackage: com.metric.**.entity.*
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true

spring:
  datasource:
    url: jdbc:mysql://192.168.64.130:3306/shu_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

knife4j:
  enable: true
  documents:
    -
      group: custom-doc-knife4j-1.1.0
      name: README
      locations: classpath:markdown/*